# Generated by Django 4.2.29 on 2026-03-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchtask",
            name="target_email",
            field=models.EmailField(default="zzj20050510@hotmail.com", max_length=254),
        ),
    ]
