# Generated by Django 4.2.29 on 2026-03-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_watchtask_target_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchtask",
            name="min_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="最低限价 (用于过滤配件)"
            ),
        ),
        migrations.AddField(
            model_name="watchtask",
            name="must_contain",
            field=models.CharField(
                blank=True,
                help_text="选填，多个词用逗号隔开。例如：GB,TB,Unlocked",
                max_length=255,
                verbose_name="必须包含的特征词",
            ),
        ),
    ]
