# Generated by Django 4.2.29 on 2026-03-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0003_watchtask_min_price_watchtask_must_contain"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchtask",
            name="is_vip",
            field=models.BooleanField(default=False, verbose_name="VIP会员"),
        ),
        migrations.AddField(
            model_name="watchtask",
            name="last_run",
            field=models.DateTimeField(blank=True, null=True, verbose_name="上次运行时间"),
        ),
    ]
