# Generated by Django 4.2.29 on 2026-03-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0004_watchtask_is_vip_watchtask_last_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchtask",
            name="check_interval",
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name="watchtask",
            name="wechat_push_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watchtask",
            name="is_vip",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="watchtask",
            name="last_run",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="watchtask",
            name="min_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="watchtask",
            name="must_contain",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
