# Generated by Django 4.2.29 on 2026-03-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0005_watchtask_check_interval_watchtask_wechat_push_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapeditem",
            name="platform",
            field=models.CharField(default="eBay", max_length=50),
        ),
        migrations.AlterField(
            model_name="watchtask",
            name="platform",
            field=models.CharField(default="All", max_length=50),
        ),
    ]
