# Generated by Django 4.2.29 on 2026-03-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0006_scrapeditem_platform_alter_watchtask_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchtask",
            name="platform",
            field=models.CharField(
                choices=[
                    ("eBay", "eBay"),
                    ("Facebook", "Facebook Marketplace"),
                    ("All", "全部平台"),
                ],
                default="All",
                max_length=50,
            ),
        ),
    ]
